### ISSUE TITLE
Debian directory in dpdk-16.07

### ISSUE THREAD

**Issue by Shelphy** [georgepar/fuel-plugin-ovs-mirror#1]
Hi folks according to the script "build-ovs-nsh-dpdk-2.6.1.sh", I found that there was no debian/ in dpdk-16.07. Could you give me some suggestion? Thanks.

**Comment by Shelphy** [comment]
Sorry, found the problem.

**Comment by georgepar** [comment]
No problem. Just keep in mind that a similar [patch](https://github.com/openstack/fuel-plugin-ovs/commit/db6380e4059dc317043e3704f63caf74c8aa6d42
) was merged in the [upstream repo](https://github.com/openstack/fuel-plugin-ovs).
This repo is not actively maintained, so you might want to use that.

**Comment by Shelphy** [comment]
Got it. Thank you George.

2017-02-07 17:39 GMT+08:00 George Paraskevopoulos <notifications@github.com>
:
